import {PlayerId} from '../common/Types';
import {CardName} from '../common/cards/CardName';
import {Color} from '../common/Color';
import {SerializedCard} from './SerializedCard';
import {SerializedTimer} from '../common/SerializedTimer';
import {AlliedParty} from '../common/turmoil/Types';
import {GlobalParameter} from '../common/GlobalParameter';
import {DiscordId} from './server/auth/discord';
import {UnderworldPlayerData} from '../common/underworld/UnderworldPlayerData';
import {ConglomeratesPlayerData} from '../common/conglomerates/ConglomeratesPlayerData';
import {DeltaProjectPlayerModel} from '../common/models/DeltaProjectPlayerModel';
import {EarlyGameStats} from './game/EarlyGameStats';
import type {ResearchPurchaseUndoState} from './game/ResearchPurchaseUndo';

interface DeprecatedFields {
}

export interface SerializedPlayer extends DeprecatedFields{
  actionsTakenThisGame: number;
  actionsTakenAtGenerationStart?: number;
  actionsTakenThisRound: number;
  availableActionsThisRound?: number;
  actionsThisGeneration: Array<CardName>;
  alliedParty: AlliedParty | undefined;
  autoPass: boolean;
  beginner: boolean;
  canUseHeatAsMegaCredits: boolean;
  // Optional for backward compatibility with games serialized before this field existed.
  canUseEnergyAsMegaCredits?: boolean;
  canUseTitaniumAsMegacredits: boolean;
  canUsePlantsAsMegaCredits: boolean;
  cardCost: number;
  cardDiscount: number;
  cardsInHand: Array<CardName>;
  ceoCardsInHand: Array<CardName>;
  colonyTradeDiscount: number;
  colonyTradeOffset: number;
  colonyVictoryPoints: number;
  color: Color;
  dealtCorporationCards: Array<CardName>;
  dealtCeoCards: Array<CardName>;
  dealtPreludeCards: Array<CardName>;
  dealtProjectCards: Array<CardName>;
  deltaProject?: DeltaProjectPlayerModel;
  epsilonDample?: DeltaProjectPlayerModel;
  draftedCards: Array<CardName>;
  draftHand: Array<CardName>,
  energy: number;
  energyProduction: number;
  earlyGameStats?: EarlyGameStats;
  fleetSize: number;
  globalParameterSteps: Record<GlobalParameter, number>;
  handicap: number;
  preludeHandicap?: number;
  hasIncreasedTerraformRatingThisGeneration: boolean;
  hasTurmoilScienceTagBonus: boolean;
  heat: number;
  heatProduction: number;
  id: PlayerId;
  jovianTagCount: number;
  lastCardPlayed?: CardName;
  lastNoticeMessageId?: number;
  lastTurnNoticeKey?: string;
  lastTurnReminderNoticeKey?: string;
  lastGreeneryActionNumber?: number;
  nextResearchKeepMax?: number;
  megaCreditProduction: number;
  megaCredits: number;
  name: string;
  needsToDraft: boolean | undefined;
  oceanBonus: number;
  pendingInitialActions: Array<CardName> | undefined;
  pickedCorporationCard: CardName | undefined;
  plantProduction: number;
  plants: number;
  plantsNeededForGreenery: number;
  plantTagCount: number;
  playedCards: Array<SerializedCard>;
  politicalAgendasActionUsedCount: number;
  preludeCardsInHand: Array<CardName>;
  preservationProgram: boolean;
  removedFromPlayCards: Array<CardName>;
  researchPurchaseUndo?: ResearchPurchaseUndoState;
  removingPlayers: Array<PlayerId>;
  scienceTagCount: number;
  spaceTagCount?: number;
  energyTagCount?: number;
  wildTagCount?: number;
  standardProjectsThisGeneration: Array<CardName>;
  steel: number;
  steelProduction: number;
  steelValue: number;
  floaterValue?: number;
  terraformRating: number;
  timer: SerializedTimer;
  titanium: number;
  titaniumProduction: number;
  titaniumValue: number;
  totalDelegatesPlaced: number;
  tradesThisGeneration: number;
  trThisGeneration: number;
  administrativeDelayActiveGeneration?: number;
  oneActionPerTurnActiveGeneration?: number;
  turmoilPolicyActionUsed: boolean;
  underworldData: UnderworldPlayerData;
  conglomeratesData?: ConglomeratesPlayerData;
  victoryPointsByGeneration: Array<number>;
  user?: DiscordId;
  telegramID?: string;
  warmongerCards: number;
  industryTilesPlaced?: number;
  withinDeflectionZone: boolean;
}
