import {MilestoneName} from './MilestoneName';

/**
 * Conglomerates milestone variants have no dedicated art (see the server's
 * ConglomeratesMilestoneVariant.ts / GeneralistConglomerates.ts) -- their badge reuses the
 * base milestone's image (see the `@ma-name-conglomerates` LESS loop in player_home.less),
 * and Milestone.vue draws a small patch over its corner number using the real value from
 * this map. `Generalist2` is deliberately absent: its meaning changed entirely (team-combined
 * production, not a simple scaled threshold), so a single patched number wouldn't represent
 * it any more accurately than the unpatched base image already does.
 */
export const CONGLOMERATES_MILESTONE_NUMBERS: Partial<Record<MilestoneName, number>> = {
  'Agronomist6': 6,
  'Architect5': 5,
  'Builder12': 12,
  'C. Forester5': 5,
  'Capitalist96': 96,
  'Coastguard5': 5,
  'Colonizer6': 6,
  'Diversifier10': 10,
  'Ecologist6': 6,
  'Economizer8': 8,
  'Energizer9': 9,
  'Engineer15': 15,
  'Farmer8': 8,
  'Firestarter30': 30,
  'Forester6': 6,
  'Fundraiser18': 18,
  'Gambler3': 3,
  'Gardener5': 5,
  'Geologist5': 5,
  'Irrigator6': 6,
  'Land Specialist5': 5,
  'Legend8': 8,
  'Martian6': 6,
  'Mayor5': 5,
  'Pioneer5': 5,
  'Planner24': 24,
  'Polar Explorer5': 5,
  'Researcher6': 6,
  'Rim Settler5': 5,
  'Smith9': 9,
  'Spacefarer9': 9,
  'Specialist15': 15,
  'T. Collector5': 5,
  'Tactician8': 8,
  'Terra Pioneer8': 8,
  'Terraformer53': 53,
  'Terran9': 9,
  'Tradesman5': 5,
  'Tropicalist5': 5,
  'Tycoon23': 23,
  'V. Electrician6': 6,
  'V. Spacefarer6': 6,
  'Hoverlord11': 11,
  'Hydrologist6': 6,
  'Landshaper5': 5,
  'Lobbyist11': 11,
  'Lunarchitect9': 9,
  'Metallurgist9': 9,
  'Networker5': 5,
  'One Giant Step9': 9,
  'Philantropist8': 8,
  'Producer24': 24,
  'Purifier5': 5,
  'Risktaker5': 5,
  'Sponsor5': 5,
  'Thawer8': 8,
  'Trader5': 5,
  'Tunneler11': 11,
};
