export const EXPANSIONS = [
  'corpera',
  'promo',
  'venus',
  'colonies',
  'prelude',
  'prelude2',
  'turmoil',
  'community',
  'ares',
  'moon',
  'pathfinders',
  'ceo',
  'starwars',
  'underworld',
  'deltaProject',
  'sillyfication',
  'betterMars',
  'customCards',
  'conglomerates',
  'corporateBetterments',
  'idesOfMars',
  'robAntilles',
  'moreParties',
  'venusPhase2',
  'industries',
  'highOrbit',
  'solaris',
] as const;

export const GAME_MODULES = [
  'base',
  ...EXPANSIONS,
] as const;
export type GameModule = typeof GAME_MODULES[number];

export type Expansion = Exclude<GameModule, 'base'>;

export const MODULE_NAMES = {
  base: 'Base',
  corpera: 'Corporate Era',
  promo: 'Promo',
  venus: 'Venus Next',
  colonies: 'Colonies',
  prelude: 'Prelude',
  prelude2: 'Prelude 2',
  turmoil: 'Turmoil',
  community: 'Community',
  ares: 'Ares',
  moon: 'The Moon',
  pathfinders: 'Pathfinders',
  ceo: 'CEOs',
  starwars: 'Star Wars',
  underworld: 'Underworld',
  deltaProject: 'Delta Project',
  sillyfication: 'Sillyfication',
  betterMars: 'BetterMars',
  customCards: 'Custom Cards',
  conglomerates: 'Conglomerates',
  corporateBetterments: 'Corporate Betterments',
  idesOfMars: 'Ides of Mars',
  robAntilles: 'Rob Antilles',
  moreParties: 'More Parties',
  venusPhase2: 'Venus: Phase 2',
  industries: 'Industries',
  highOrbit: 'High Orbit',
  solaris: 'Solaris',
} satisfies Record<GameModule, string>;

export const DEFAULT_EXPANSIONS = {
  corpera: true,
  promo: false,
  venus: false,
  colonies: false,
  prelude: false,
  prelude2: false,
  turmoil: false,
  community: false,
  ares: false,
  moon: false,
  pathfinders: false,
  ceo: false,
  starwars: false,
  underworld: false,
  deltaProject: false,
  sillyfication: false,
  betterMars: false,
  customCards: false,
  conglomerates: false,
  corporateBetterments: false,
  idesOfMars: false,
  robAntilles: false,
  moreParties: false,
  venusPhase2: false,
  industries: false,
  highOrbit: false,
  solaris: false,
} satisfies Record<Expansion, boolean>;
