export enum Tag {
    BUILDING = 'building',
    SPACE = 'space',
    SCIENCE = 'science',
    POWER = 'power',
    EARTH = 'earth',
    JOVIAN = 'jovian',
    VENUS = 'venus',
    PLANT = 'plant',
    MICROBE = 'microbe',
    ANIMAL = 'animal',
    CITY = 'city',
    MOON = 'moon',
    MARS = 'mars',
    CRIME = 'crime',
    WILD = 'wild',
    EVENT = 'event',
    CLONE = 'clone',
    // High Orbit (fan): carried by every "Silver" card.
    INFRASTRUCTURE = 'infrastructure',
    // Solaris (fan): carried by a subset of very expensive, high-payoff cards.
    GALACTIC = 'galactic',
}

export const ALL_TAGS = [
  Tag.BUILDING,
  Tag.SPACE,
  Tag.SCIENCE,
  Tag.POWER,
  Tag.EARTH,
  Tag.JOVIAN,
  Tag.VENUS,
  Tag.MOON,
  Tag.MARS,
  Tag.PLANT,
  Tag.MICROBE,
  Tag.ANIMAL,
  Tag.CRIME,
  Tag.CITY,
  Tag.WILD,
  Tag.EVENT,
  Tag.CLONE,
  Tag.INFRASTRUCTURE,
  Tag.GALACTIC,
] as const;
