import * as constants from '@/common/constants';
import {BoardName} from '@/common/boards/BoardName';
import {DEFAULT_EXPANSIONS} from '@/common/cards/GameModule';
import {RandomMAOptionType} from '@/common/ma/RandomMAOptionType';
import {CreateGameModel} from './CreateGameModel';

export function defaultCreateGameModel(): CreateGameModel {
  return {
    firstIndex: 1,
    playersCount: 1,
    players: [
      {name: '', color: 'red', beginner: false, handicap: 0, preludeHandicap: 2, first: false, isBot: false, telegramID: ''},
      {name: '', color: 'green', beginner: false, handicap: 0, preludeHandicap: 2, first: false, isBot: false, telegramID: ''},
      {name: '', color: 'yellow', beginner: false, handicap: 0, preludeHandicap: 2, first: false, isBot: false, telegramID: ''},
      {name: '', color: 'blue', beginner: false, handicap: 0, preludeHandicap: 2, first: false, isBot: false, telegramID: ''},
      {name: '', color: 'black', beginner: false, handicap: 0, preludeHandicap: 2, first: false, isBot: false, telegramID: ''},
      {name: '', color: 'purple', beginner: false, handicap: 0, preludeHandicap: 2, first: false, isBot: false, telegramID: ''},
      {name: '', color: 'orange', beginner: false, handicap: 0, preludeHandicap: 2, first: false, isBot: false, telegramID: ''},
      {name: '', color: 'pink', beginner: false, handicap: 0, preludeHandicap: 2, first: false, isBot: false, telegramID: ''},
    ],
    expansions: {...DEFAULT_EXPANSIONS},
    draftVariant: true,
    initialDraft: false,
    initialDraftOneWay: false,
    randomMA: RandomMAOptionType.NONE,
    modularMA: false,
    noEloGame: false,
    privateHands: true,
    turnBasedGame: false,
    botGame: false,
    randomFirstPlayer: true,
    showOtherPlayersVP: false,
    // beginnerOption: false,
    showCeosList: false,
    showColoniesList: false,
    showCorporationList: false,
    showPreludesList: false,
    showBannedCards: false,
    showIncludedCards: false,
    customCeos: [],
    customColonies: [],
    customCorporations: [],
    customPreludes: [],
    bannedCards: [],
    includedCards: [],
    board: BoardName.THARSIS,
    seed: Math.random(),
    seededGame: false,
    solarPhaseOption: true,
    shuffleMapOption: false,
    aresExtremeVariant: false,
    politicalAgendasExtension: 'Standard',
    undoOption: false,
    showTimers: true,
    fastModeOption: false,
    removeNegativeGlobalEventsOption: false,
    includeFanMA: false,
    startingCorporations: 2,
    soloTR: false,
    clonedGameId: undefined,
    allOfficialExpansions: false,
    requiresVenusTrackCompletion: false,
    requiresMoonTrackCompletion: false,
    moonStandardProjectVariant: false,
    moonStandardProjectVariant1: false,
    altVenusBoard: false,
    escapeVelocityMode: false,
    escapeVelocityThreshold: constants.DEFAULT_ESCAPE_VELOCITY_THRESHOLD,
    escapeVelocityBonusSeconds: constants.DEFAULT_ESCAPE_VELOCITY_BONUS_SECONDS,
    escapeVelocityPeriod: constants.DEFAULT_ESCAPE_VELOCITY_PERIOD,
    escapeVelocityPenalty: constants.DEFAULT_ESCAPE_VELOCITY_PENALTY,
    twoCorpsVariant: false,
    startingCeos: 3,
    startingPreludes: 4,
    preludeDraftVariant: undefined,
    ceosDraftVariant: undefined,
  };
}
